### ISSUE TITLE
Combining efforts with proxyscrape

### ISSUE THREAD

**Issue by stefanct** [narkhedesam/Proxy-List-Scrapper#1]
There exists some other similar libraries. From what I can tell the most complete is https://github.com/JaredLGillespie/proxyscrape

It would certainly make sense to cooperate instead of working separately if there are no good reasons against that...?

**Comment by narkhedesam** [comment]
Hello @stefanct,

Thanks for the information. I didn't check the available repository [proxyscrape](https://github.com/JaredLGillespie/proxyscrape). 

I think that I need to contribute in it. Also closing this issue

Thanks.
