### ISSUE TITLE
how to know which type of proxy whether https.socks5.socks4 or http

### ISSUE THREAD

**Issue by kobbycyber** [narkhedesam/Proxy-List-Scrapper#7]
thanks for code but i will be happy if u guys can add proxy type like the proxy| port |type

**Comment by narkhedesam** [comment]
Thanks for your reply...I've checked the free proxy providers but some of them not provides the exact protocol for the given proxies like proxynova.

I recommend you use the proxy checker to check these proxies for getting the exact protocol for the proxy.
here the one that provides the functionality in python https://pypi.org/project/proxy-checker/
