### ISSUE TITLE
SPYS.ME returning empty list

### ISSUE THREAD

**Issue by LeoFCardoso** [narkhedesam/Proxy-List-Scrapper#8]
**Describe the bug**
When call SPY.ME category, result is empty list

**To Reproduce**
        scrapper = Scrapper(category='SPYS.ME', print_err_trace=True)
        scrapper_proxies_full = scrapper.getProxies()  # Blank result

**Expected behavior**
Proxies populated in result list.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Python 3.7 Macos, latest version (0.2.1)

**Smartphone (please complete the following information):**
N/A

**Additional context**
I think you should work with "elif" instead of "if" in Scrapper._get() method.
Great work, thanks.

**Comment by narkhedesam** [comment]
Thanks for your report I'm looking into it to fix it ASAP

and also thanks for the suggestions to improve the if condition

**Comment by LeoFCardoso** [comment]
Working!
